import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/layouts/side-bar/sideBar";
import TopBar from "@/components/layouts/top-bar/top-bar";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import Providers from "@/redux/Provider";

const montserrat = Montserrat({
  subsets: ["cyrillic-ext"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    redirect("/auth/login");
  }

  // const data = {};
  return (
    <html lang="en">
      <body className={cn("font-montserrat", montserrat.variable)}>
        <Providers>
          <div className="w-full min-h-screen hidden bg-red-400 max-lg:flex justify-center place-items-center">
            <h1 className="text-2xl">
              Please open the app on a bigger screen or Computer
            </h1>
          </div>
          <div className="relative flex place-items-start justify-center w-full min-h-screen h-screen bg-darkBg px-8 gap-10 max-lg:hidden overflow-y-scroll overflow-x-hidden no-scrollbar">
            <SideBar />
            <div className="flex flex-col justify-start place-items-start w-full min-h-full h-full relative">
              <TopBar data={data} />
              {children}
            </div>
          </div>
          <Sonner />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
